file:
    source: https://www.formulare-bfinv.de/printout/034122.pdf
    font_family: Helvetica
    font_size: 10
    page_size: A4
    locale: de_DE.utf-8

# Not needed for original document
#box:
#   box1:
#       area: [[430, 600],
#                    [55, 18]]
#       color: [1, 1, 1]

pages:
    page1:
        cross:
            cross1:
                area: [[435, 561.5],
                       [9, 9]]
                color: [1, 0, 0]
            cross2:
                area: [[59.5, 528],
                       [9, 9]]
                color: [1, 0, 0]

        text:
            # Fixed text
            aussteller:
                position: [50, 755]
                label: >
                    Flipdot e.V.<br />
                    Sickingenstrasse 10<br />
                    34117 Kassel
            foerderung1:
                position: [81, 481]
                dimension: [450, 0]
                label: >
                    Anregung u. Unterstützg wissenschaftl. und künstler. Arbeiten zu techn. Themen; Vermittlung von technischen
                    Kenntnissen auf Veranstaltungen und durch Veröffentlichungen; Internationalen Austausch
                    über wissenschaftliche und künstlerische Arbeiten sowie internationale Veröffentlichungen.
            foerderung2:
                position: [51, 260]
                dimension: [490, 0]
                label: >
                    Anregung u. Unterstützg wissenschaftl. und künstler. Arbeiten zu techn. Themen; Vermittlung von technischen
                    Kenntnissen auf Veranstaltungen und durch Veröffentlichungen; Internationalen Austausch
                    über wissen- schaftliche und künstlerische Arbeiten sowie internationale Veröffentlichungen.
            finanzamt:
                position: [81, 453.5]
                label: Kassel 1
            stnr:
                position: [246, 453.5]
                label: 02525051902
            stnrdate:
                position: [381, 453.5]
                label: 04.11.2015
            zeitraum:
                position: [189, 439]
                label: 2011 – 2013
            location:
                position: [44, 152]
                label: Kassel,

            # Dynamic text
            today:
                position: [82, 152]
                function: today
                arguments:
                    format: '%d. %B %Y'
            phonetic:
                position: [180, 602]
                function: phonetic
                arguments:
                    value: $amount

            # Variable text
            name:
                position: [50, 675]
                file_name: True
            street:
                position: [50, 663]
            city:
                position: [50, 651]
            amount:
                position: [50, 602]
                function: currency
                arguments:
                    value: $amount
                    grouping: True
            date:
                position: [434, 602]
